remote_theme: Jekyll-fractal

# Site settings
title: COVID Aware
email: hello@jonathanrankin.com
description: Just a simple, single page responsive template brought to you by HTML5 UP.
# baseurl: "covid19-caribbean-website/" # the subpath of your site, e.g. /blog
# url: "https://edinburgh-college-of-art.github.io/" # the base hostname & protocol for your site e.g. http://yvesespinosa.com
download_button_url: "https://beta.covid-aware.org/guide"

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url:
twitter_url:  

# Build settings
markdown: kramdown
